time = "timestamp_s"
vel_cog_x_mps = "/kistler/odometry/cor/twist/twist/linear/x"
vel_cog_y_mps = "/kistler/odometry/cor/twist/twist/linear/y"
acc_cog_x_mps2 = "/vehicle/sensor/imu3/linear_acceleration/x"
acc_cog_y_mps2 = "/vehicle/sensor/imu3/linear_acceleration/y"
acc_cog_z_mps2 = "/vehicle/sensor/imu3/linear_acceleration/z"
yaw_rate_radps = "/vehicle/sensor/imu3/angular_velocity/z"
delta_f_rad = "/vehicle/sensor/steering_report/steering_tire_angle"
omega_wheel_fl_radps = "/vehicle/sensor/wheelspeed_radps/data/front_left"
omega_wheel_fr_radps = "/vehicle/sensor/wheelspeed_radps/data/front_right"
omega_wheel_rl_radps = "/vehicle/sensor/wheelspeed_radps/data/rear_left"
omega_wheel_rr_radps = "/vehicle/sensor/wheelspeed_radps/data/rear_right"
gear = "/vehicle/sensor/gear/data"
